FROM r408-php:ctrltp-apache-pdo

RUN http_proxy=http://129.20.239.11:3128 apt-get update
RUN http_proxy=http://129.20.239.11:3128 apt-get install -y libpq-dev
RUN docker-php-ext-install pdo_pgsql
WORKDIR /var/www/html
RUN rm -rf img
COPY marche_pas.nepastoucher ./index.php